### ISSUE TITLE
Updating a metadata download

### ISSUE THREAD

**Issue by karthik** [ropensci/rdryad#2]
I wrote a new function called `updatealldryad_metadata`. The idea is that if you already have a downloaded dryadmetadata.csv, you can run update to get newer records and not wait forever. The function will let you overwrite the file or create a new one. If you don't specify a new filename, it just appends date_time to the current filename.

Issue: It seems like there is no way to just get the identifiers and do a diff. This is likely due to the fact that in the `getalldryad_metadata ` function, it downloads everything, then removes records with no metadata. This seems to throw off the diff. I will work on this again over the weekend but if you guys have any quick fixes, that would be great.

**Comment by sckott** [comment]
closing, removing these download all metadata fxns
