### ISSUE TITLE
No corresponding file found

### ISSUE THREAD

**Issue by Rekyt** [ropensci/rdryad#22]
Hi,
First, thanks for building `rdryad` =) it's nice to have a package to directly manage Dryad repositories.

I stumbled upon an interesting dataset from Dryad the DOI of the article is `10.1111/ecog.01986` and I can find it on Dryad:

```
q = rdryad::d_solr_search(q = "10.1111/ecog.01986")
q$handle
# [1] "10255/dryad.116170"
```

I get the handle back but can't seem to download data from it:

```
rdryad::download_url("10255/dryad.116170")
# Error: No output from search
```

Looking at query `all_ac` field, there is another handle mentioned `10255/dryad.116171`

```
rdryad::download_url("10255/dryad.116171")
# [1] "http://datadryad.org/bitstream/handle/10255/dryad.116171/DryadArchive.zip?sequence=1"
```

This one works. Do you know why? Is it proper to Dryad's architecture? Is there a way to programmatically extract this second handle?

**Comment by sckott** [comment]
changes in b6819b5 

@Rekyt reinstlal from github `devtools::install_github("ropensci/rdryad")` - 

changed `download_url` to take a DOI or a Dryad handle. The function was only correctly dealing with handles before now. 

I updated `rdryad` to use `solrium` instead of `solr` 

in terms of using `d_solr_search`, see the `dc.identifier` field which gives the DOI for the dataset, actually gives two for your query , or the `dc.identifier.uri` field which gives the handle identifiers in a URI format

does that help?

**Comment by Rekyt** [comment]
Ok, I updated the package.
It does work with the good DOI `10.5061/dryad.9t0n8/1` which is the second one in `dc.identifier` field. So whenever downloading data, I should look at this field, parse it, and take the second one?

Dryad's architecture is not very clear to me, why would a data archive with a single file would have two DOIs? I'll try to look at other dryad repositories to see if they show the same problem.

It seems to be the same for example for doi:10.5061/dryad.s58qh, doi:10.5061/dryad.855pg has many files to download, each one has a specific DOI.

```r
a = rdryad::d_solr_search(q = "10.5061/dryad.s58qh")
# http://datadryad.org/solr/search/select?q=10.5061/dryad.s58qh&wt=json
a$dc.identifier
# [1] "doi:10.5061/dryad.s58qh,doi:10.5061/dryad.s58qh/1"
```

```r
a = rdryad::d_solr_search(q = "10.5061/dryad.855pg")
# http://datadryad.org/solr/search/select?q=10.5061/dryad.855pg&wt=json
a$dc.identifier
# [1] "doi:10.5061/dryad.855pg,doi:10.5061/dryad.855pg/1,doi:10.5061/dryad.855pg/2,doi:10.5061/dryad.855pg/3,doi:10.5061/dryad.855pg/4,doi:10.5061/dryad.855pg/5,doi:10.5061/dryad.855pg/6,doi:10.5061/dryad.855pg/7,doi:10.5061/dryad.855pg/8,doi:10.5061/dryad.855pg/9,doi:10.5061/dryad.855pg/10,doi:10.5061/dryad.855pg/11,doi:10.5061/dryad.855pg/12,doi:10.5061/dryad.855pg/13,doi:10.5061/dryad.855pg/14"
```

So actually the first DOI is only for the **data package** while all the other ones are for the **data files**. And similarly for the package. It was unclear to me because looking at the examples I thought a single handle was enough to download all files, but looking back at them they had different handles than their data packages.

**Comment by sckott** [comment]
sorry about the confusion, it confuses me too. 

> So whenever downloading data, I should look at this field, parse it, and take the second one?

yes, that should work

> Dryad's architecture is not very clear to me, why would a data archive with a single file would have two DOIs?

it sorta makes sense - the DOI without the end slash and number part leads to the landing page for the data package, and any DOIs with `/1`, etc. are for individual data files

> So actually the first DOI is only for the data package while all the other ones are for the data files. 

right. 

I'll try to clarify in the examples how people can do this. maybe even a helper function to get all the DOIs for individual data files for a data package

**Comment by sckott** [comment]
in commit 4c9e364 added a new function `dryad_package_dois` to fetch the individual file DOIs from a package DOI - adding some examples now
