### ISSUE TITLE
new Dryad API

### ISSUE THREAD

**Issue by sckott** [ropensci/rdryad#28]
https://datadryad.org/api/v2/docs/

**Comment by sckott** [comment]
@karthik let me know if you want to take over here with the new Dryad API or if you want me to

**Comment by karthik** [comment]
Yes please. Happy to take over. 🙏

**Comment by sckott** [comment]
okay, made you maintainer in last commit

**Comment by karthik** [comment]
Thanks Scott, appreciate it.
