### ISSUE TITLE
Not able to download files with r dryad

### ISSUE THREAD

**Issue by matisscastor** [ropensci/rdryad#30]
Hi!

I am running the commands from your examples and the don't seem to work. For instance, when running the following command that you offer as an example:

x <- dryad_files('10.5061/dryad.1758')
x
[1] "http://datadryad.org"

Instead of showing:

dryad_files('10.5061/dryad.1758')
#> [1] "http://datadryad.org/bitstream/handle/10255/dryad.1759/dataset.csv?sequence=1"
#> [2] "http://datadryad.org/bitstream/handle/10255/dryad.1759/README.txt?sequence=2"

Thanks!

**Comment by sckott** [comment]
hi @matisscastor - thanks for your question. please supply your R session info with rdyrad loaded, as requested

**Comment by rdinnager** [comment]
I have the same issue. My session info:

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rdryad_0.4.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       crayon_1.3.4     assertthat_0.2.1 dplyr_0.8.5      crul_0.9.0       R6_2.4.1         plyr_1.8.5      
 [8] jsonlite_1.6.1   magrittr_1.5     pillar_1.4.3     httr_1.4.1       rlang_0.4.5      stringi_1.4.6    curl_4.3        
[15] rstudioapi_0.11  xml2_1.2.2       oai_0.3.0        tools_3.6.2      stringr_1.4.0    glue_1.3.2       purrr_0.3.3     
[22] compiler_3.6.2   pkgconfig_2.0.3  tidyselect_1.0.0 tibble_2.1.3     solrium_1.1.4    httpcode_0.2.0  
```

**Comment by sckott** [comment]
@matisscastor @rdinnager Dryad has a new API. see the branch `new-dryad-api` https://github.com/ropensci/rdryad/compare/new-dryad-api?w=1 - it's in development. the new API is not exactly working completely, some things work, and some do not work.

**Comment by sckott** [comment]
asking dryad for feedback to see if we can fix some things

**Comment by rdinnager** [comment]
Okay, thanks for the update!

**Comment by sckott** [comment]
they said 2 weeks out from a fix

**Comment by matisscastor** [comment]
Hi any updates? Still can't download files from dryad using rdryad.

**Comment by sckott** [comment]
i'll try to get to it today

**Comment by sckott** [comment]
@matisscastor try restarting R, then reinstalling `remotes::install_github("ropensci/rdryad")`,  then see `?dryad_download` - still working on other functions in the package, working out errors going on with the new dryad API

**Comment by sckott** [comment]
@matisscastor  @rdinnager changes are on master branch now, sending to cran soon. Following he new Dryad API - all functions for solr and oai-pmh services are defunct. See docs https://docs.ropensci.org/rdryad/ 

The function `dryad_files` exists in the new version but it doesn't do the same thing. See the docs.

Closing this issue since the functions in rdryad have totally changed. Please open new issues if you run into problems
