### ISSUE TITLE
Can't pass arguments to dryad_datasets

### ISSUE THREAD

**Issue by karthik** [ropensci/rdryad#38]
All these calls return the same results:

```
dryad_datasets()
dryad_datasets(per_page = 25, page = 2)
dryad_datasets(per_page = 200)
```

This means that the `page` and `per_page` ([Dryad API docs](https://datadryad.org/api/v2/docs/#/datasets/get_datasets)) are not getting passed on. This should be a simple fix according to @mpadge 

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/138494/172205837-fbbad370-ec6b-4375-9f08-10b1c3fa6256.png">

**Comment by mpadge** [comment]
All should work now. @karthik This never made it back on to CRAN, but let me know if it would help you to have it there, and I'll reinstate it until {deposits} gets there. That said, there have been no inquiries about it being archived, and so I'd personally prefer to just wait for {deposits}, if that's okay with you.

**Comment by karthik** [comment]
Perfect, thanks!

>  This never made it back on to CRAN, but let me know if it would help you to have it there

I don't think so. Since this will all get folded into deposits, let's not confuse users.
