### ISSUE TITLE
lapply error with datasets.

### ISSUE THREAD

**Issue by emhart** [ropensci/rdryad#4]
I've come across this with multiple data sets.  Here's the data-set I want:
http://datadryad.org/resource/doi:10.5061/dryad.1664

`dryaddat <- download_url("10255/dryad.1664")`
`Error in out[lapply(out, str_detect, pattern = "sequence=1") == "TRUE"][[1]] : 
  subscript out of bounds`

**Comment by sckott** [comment]
closed in 9f4d531
